#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_WareHouse
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKhoBenBai")]
	public partial class QuanLyKhoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHI_TIET_PHIEU_DAT(CHI_TIET_PHIEU_DAT instance);
    partial void UpdateCHI_TIET_PHIEU_DAT(CHI_TIET_PHIEU_DAT instance);
    partial void DeleteCHI_TIET_PHIEU_DAT(CHI_TIET_PHIEU_DAT instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertDM_MANHINH(DM_MANHINH instance);
    partial void UpdateDM_MANHINH(DM_MANHINH instance);
    partial void DeleteDM_MANHINH(DM_MANHINH instance);
    partial void InsertKE_HANG(KE_HANG instance);
    partial void UpdateKE_HANG(KE_HANG instance);
    partial void DeleteKE_HANG(KE_HANG instance);
    partial void InsertKHU_VUC(KHU_VUC instance);
    partial void UpdateKHU_VUC(KHU_VUC instance);
    partial void DeleteKHU_VUC(KHU_VUC instance);
    partial void InsertNGUOIDUNG_NHOMNGUOIDUNG(NGUOIDUNG_NHOMNGUOIDUNG instance);
    partial void UpdateNGUOIDUNG_NHOMNGUOIDUNG(NGUOIDUNG_NHOMNGUOIDUNG instance);
    partial void DeleteNGUOIDUNG_NHOMNGUOIDUNG(NGUOIDUNG_NHOMNGUOIDUNG instance);
    partial void InsertPHIEU_DAT_HANG(PHIEU_DAT_HANG instance);
    partial void UpdatePHIEU_DAT_HANG(PHIEU_DAT_HANG instance);
    partial void DeletePHIEU_DAT_HANG(PHIEU_DAT_HANG instance);
    partial void InsertQL_NHOMNGUOIDUNG(QL_NHOMNGUOIDUNG instance);
    partial void UpdateQL_NHOMNGUOIDUNG(QL_NHOMNGUOIDUNG instance);
    partial void DeleteQL_NHOMNGUOIDUNG(QL_NHOMNGUOIDUNG instance);
    partial void InsertQL_PHANQUYEN(QL_PHANQUYEN instance);
    partial void UpdateQL_PHANQUYEN(QL_PHANQUYEN instance);
    partial void DeleteQL_PHANQUYEN(QL_PHANQUYEN instance);
    partial void InsertNHA_CUNG_CAP(NHA_CUNG_CAP instance);
    partial void UpdateNHA_CUNG_CAP(NHA_CUNG_CAP instance);
    partial void DeleteNHA_CUNG_CAP(NHA_CUNG_CAP instance);
    partial void InsertNHAN_VIEN(NHAN_VIEN instance);
    partial void UpdateNHAN_VIEN(NHAN_VIEN instance);
    partial void DeleteNHAN_VIEN(NHAN_VIEN instance);
    partial void InsertHANG_HOA(HANG_HOA instance);
    partial void UpdateHANG_HOA(HANG_HOA instance);
    partial void DeleteHANG_HOA(HANG_HOA instance);
    partial void InsertCHI_TIET_PHIEU_XUAT(CHI_TIET_PHIEU_XUAT instance);
    partial void UpdateCHI_TIET_PHIEU_XUAT(CHI_TIET_PHIEU_XUAT instance);
    partial void DeleteCHI_TIET_PHIEU_XUAT(CHI_TIET_PHIEU_XUAT instance);
    partial void InsertPHIEU_XUAT_KHO(PHIEU_XUAT_KHO instance);
    partial void UpdatePHIEU_XUAT_KHO(PHIEU_XUAT_KHO instance);
    partial void DeletePHIEU_XUAT_KHO(PHIEU_XUAT_KHO instance);
    #endregion
		
		public QuanLyKhoDataContext() : 
				base(global::DAL_WareHouse.Properties.Settings.Default.QLKhoBenBaiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyKhoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyKhoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyKhoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyKhoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHI_TIET_PHIEU_DAT> CHI_TIET_PHIEU_DATs
		{
			get
			{
				return this.GetTable<CHI_TIET_PHIEU_DAT>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<DM_MANHINH> DM_MANHINHs
		{
			get
			{
				return this.GetTable<DM_MANHINH>();
			}
		}
		
		public System.Data.Linq.Table<KE_HANG> KE_HANGs
		{
			get
			{
				return this.GetTable<KE_HANG>();
			}
		}
		
		public System.Data.Linq.Table<KHU_VUC> KHU_VUCs
		{
			get
			{
				return this.GetTable<KHU_VUC>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG_NHOMNGUOIDUNG> NGUOIDUNG_NHOMNGUOIDUNGs
		{
			get
			{
				return this.GetTable<NGUOIDUNG_NHOMNGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<PHIEU_DAT_HANG> PHIEU_DAT_HANGs
		{
			get
			{
				return this.GetTable<PHIEU_DAT_HANG>();
			}
		}
		
		public System.Data.Linq.Table<QL_NHOMNGUOIDUNG> QL_NHOMNGUOIDUNGs
		{
			get
			{
				return this.GetTable<QL_NHOMNGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<QL_PHANQUYEN> QL_PHANQUYENs
		{
			get
			{
				return this.GetTable<QL_PHANQUYEN>();
			}
		}
		
		public System.Data.Linq.Table<HANG_HOA_TTCB> HANG_HOA_TTCBs
		{
			get
			{
				return this.GetTable<HANG_HOA_TTCB>();
			}
		}
		
		public System.Data.Linq.Table<NHA_CUNG_CAP> NHA_CUNG_CAPs
		{
			get
			{
				return this.GetTable<NHA_CUNG_CAP>();
			}
		}
		
		public System.Data.Linq.Table<NHAN_VIEN> NHAN_VIENs
		{
			get
			{
				return this.GetTable<NHAN_VIEN>();
			}
		}
		
		public System.Data.Linq.Table<HANG_HOA> HANG_HOAs
		{
			get
			{
				return this.GetTable<HANG_HOA>();
			}
		}
		
		public System.Data.Linq.Table<CHI_TIET_PHIEU_XUAT> CHI_TIET_PHIEU_XUATs
		{
			get
			{
				return this.GetTable<CHI_TIET_PHIEU_XUAT>();
			}
		}
		
		public System.Data.Linq.Table<PHIEU_XUAT_KHO> PHIEU_XUAT_KHOs
		{
			get
			{
				return this.GetTable<PHIEU_XUAT_KHO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHI_TIET_PHIEU_DAT")]
	public partial class CHI_TIET_PHIEU_DAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_CTPD;
		
		private string _MAPHIEUDAT;
		
		private string _MAMATHANG;
		
		private decimal _SOLUONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_CTPDChanging(string value);
    partial void OnMA_CTPDChanged();
    partial void OnMAPHIEUDATChanging(string value);
    partial void OnMAPHIEUDATChanged();
    partial void OnMAMATHANGChanging(string value);
    partial void OnMAMATHANGChanged();
    partial void OnSOLUONGChanging(decimal value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public CHI_TIET_PHIEU_DAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_CTPD", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_CTPD
		{
			get
			{
				return this._MA_CTPD;
			}
			set
			{
				if ((this._MA_CTPD != value))
				{
					this.OnMA_CTPDChanging(value);
					this.SendPropertyChanging();
					this._MA_CTPD = value;
					this.SendPropertyChanged("MA_CTPD");
					this.OnMA_CTPDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUDAT", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAPHIEUDAT
		{
			get
			{
				return this._MAPHIEUDAT;
			}
			set
			{
				if ((this._MAPHIEUDAT != value))
				{
					this.OnMAPHIEUDATChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUDAT = value;
					this.SendPropertyChanged("MAPHIEUDAT");
					this.OnMAPHIEUDATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMATHANG", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAMATHANG
		{
			get
			{
				return this._MAMATHANG;
			}
			set
			{
				if ((this._MAMATHANG != value))
				{
					this.OnMAMATHANGChanging(value);
					this.SendPropertyChanging();
					this._MAMATHANG = value;
					this.SendPropertyChanged("MAMATHANG");
					this.OnMAMATHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Decimal(18,0) NOT NULL")]
		public decimal SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TENDN;
		
		private string _MATKHAU;
		
		private System.Nullable<bool> _HOATDONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnHOATDONGChanging(System.Nullable<bool> value);
    partial void OnHOATDONGChanged();
    #endregion
		
		public TAIKHOAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="Char(10)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOATDONG", DbType="Bit")]
		public System.Nullable<bool> HOATDONG
		{
			get
			{
				return this._HOATDONG;
			}
			set
			{
				if ((this._HOATDONG != value))
				{
					this.OnHOATDONGChanging(value);
					this.SendPropertyChanging();
					this._HOATDONG = value;
					this.SendPropertyChanged("HOATDONG");
					this.OnHOATDONGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_MANHINH")]
	public partial class DM_MANHINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAMANHINH;
		
		private string _TENMANHINH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAMANHINHChanging(string value);
    partial void OnMAMANHINHChanged();
    partial void OnTENMANHINHChanging(string value);
    partial void OnTENMANHINHChanged();
    #endregion
		
		public DM_MANHINH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMANHINH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAMANHINH
		{
			get
			{
				return this._MAMANHINH;
			}
			set
			{
				if ((this._MAMANHINH != value))
				{
					this.OnMAMANHINHChanging(value);
					this.SendPropertyChanging();
					this._MAMANHINH = value;
					this.SendPropertyChanged("MAMANHINH");
					this.OnMAMANHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENMANHINH", DbType="VarChar(20)")]
		public string TENMANHINH
		{
			get
			{
				return this._TENMANHINH;
			}
			set
			{
				if ((this._TENMANHINH != value))
				{
					this.OnTENMANHINHChanging(value);
					this.SendPropertyChanging();
					this._TENMANHINH = value;
					this.SendPropertyChanged("TENMANHINH");
					this.OnTENMANHINHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KE_HANG")]
	public partial class KE_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKEHANG;
		
		private string _MAKV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKEHANGChanging(string value);
    partial void OnMAKEHANGChanged();
    partial void OnMAKVChanging(string value);
    partial void OnMAKVChanged();
    #endregion
		
		public KE_HANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKEHANG", DbType="Char(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKEHANG
		{
			get
			{
				return this._MAKEHANG;
			}
			set
			{
				if ((this._MAKEHANG != value))
				{
					this.OnMAKEHANGChanging(value);
					this.SendPropertyChanging();
					this._MAKEHANG = value;
					this.SendPropertyChanged("MAKEHANG");
					this.OnMAKEHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKV", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAKV
		{
			get
			{
				return this._MAKV;
			}
			set
			{
				if ((this._MAKV != value))
				{
					this.OnMAKVChanging(value);
					this.SendPropertyChanging();
					this._MAKV = value;
					this.SendPropertyChanged("MAKV");
					this.OnMAKVChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHU_VUC")]
	public partial class KHU_VUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKV;
		
		private string _TENKV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKVChanging(string value);
    partial void OnMAKVChanged();
    partial void OnTENKVChanging(string value);
    partial void OnTENKVChanged();
    #endregion
		
		public KHU_VUC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKV
		{
			get
			{
				return this._MAKV;
			}
			set
			{
				if ((this._MAKV != value))
				{
					this.OnMAKVChanging(value);
					this.SendPropertyChanging();
					this._MAKV = value;
					this.SendPropertyChanged("MAKV");
					this.OnMAKVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKV", DbType="NVarChar(50)")]
		public string TENKV
		{
			get
			{
				return this._TENKV;
			}
			set
			{
				if ((this._TENKV != value))
				{
					this.OnTENKVChanging(value);
					this.SendPropertyChanging();
					this._TENKV = value;
					this.SendPropertyChanged("TENKV");
					this.OnTENKVChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG_NHOMNGUOIDUNG")]
	public partial class NGUOIDUNG_NHOMNGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TENDN;
		
		private string _MANHOMNGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    partial void OnMANHOMNGUOIDUNGChanging(string value);
    partial void OnMANHOMNGUOIDUNGChanged();
    #endregion
		
		public NGUOIDUNG_NHOMNGUOIDUNG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHOMNGUOIDUNG", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHOMNGUOIDUNG
		{
			get
			{
				return this._MANHOMNGUOIDUNG;
			}
			set
			{
				if ((this._MANHOMNGUOIDUNG != value))
				{
					this.OnMANHOMNGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._MANHOMNGUOIDUNG = value;
					this.SendPropertyChanged("MANHOMNGUOIDUNG");
					this.OnMANHOMNGUOIDUNGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEU_DAT_HANG")]
	public partial class PHIEU_DAT_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHIEUDAT;
		
		private string _MANCC;
		
		private string _MANV;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHIEUDATChanging(string value);
    partial void OnMAPHIEUDATChanged();
    partial void OnMANCCChanging(string value);
    partial void OnMANCCChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnNGAYLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPChanged();
    #endregion
		
		public PHIEU_DAT_HANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIEUDAT", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHIEUDAT
		{
			get
			{
				return this._MAPHIEUDAT;
			}
			set
			{
				if ((this._MAPHIEUDAT != value))
				{
					this.OnMAPHIEUDATChanging(value);
					this.SendPropertyChanging();
					this._MAPHIEUDAT = value;
					this.SendPropertyChanged("MAPHIEUDAT");
					this.OnMAPHIEUDATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="Char(10)")]
		public string MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NHOMNGUOIDUNG")]
	public partial class QL_NHOMNGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANHOMNGUOIDUNG;
		
		private string _TENNHOMNGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHOMNGUOIDUNGChanging(string value);
    partial void OnMANHOMNGUOIDUNGChanged();
    partial void OnTENNHOMNGUOIDUNGChanging(string value);
    partial void OnTENNHOMNGUOIDUNGChanged();
    #endregion
		
		public QL_NHOMNGUOIDUNG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHOMNGUOIDUNG", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHOMNGUOIDUNG
		{
			get
			{
				return this._MANHOMNGUOIDUNG;
			}
			set
			{
				if ((this._MANHOMNGUOIDUNG != value))
				{
					this.OnMANHOMNGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._MANHOMNGUOIDUNG = value;
					this.SendPropertyChanged("MANHOMNGUOIDUNG");
					this.OnMANHOMNGUOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNHOMNGUOIDUNG", DbType="VarChar(20)")]
		public string TENNHOMNGUOIDUNG
		{
			get
			{
				return this._TENNHOMNGUOIDUNG;
			}
			set
			{
				if ((this._TENNHOMNGUOIDUNG != value))
				{
					this.OnTENNHOMNGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._TENNHOMNGUOIDUNG = value;
					this.SendPropertyChanged("TENNHOMNGUOIDUNG");
					this.OnTENNHOMNGUOIDUNGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_PHANQUYEN")]
	public partial class QL_PHANQUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANHOMNGUOIDUNG;
		
		private string _MAMANHINH;
		
		private System.Nullable<bool> _COQUYEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANHOMNGUOIDUNGChanging(string value);
    partial void OnMANHOMNGUOIDUNGChanged();
    partial void OnMAMANHINHChanging(string value);
    partial void OnMAMANHINHChanged();
    partial void OnCOQUYENChanging(System.Nullable<bool> value);
    partial void OnCOQUYENChanged();
    #endregion
		
		public QL_PHANQUYEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHOMNGUOIDUNG", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANHOMNGUOIDUNG
		{
			get
			{
				return this._MANHOMNGUOIDUNG;
			}
			set
			{
				if ((this._MANHOMNGUOIDUNG != value))
				{
					this.OnMANHOMNGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._MANHOMNGUOIDUNG = value;
					this.SendPropertyChanged("MANHOMNGUOIDUNG");
					this.OnMANHOMNGUOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMANHINH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAMANHINH
		{
			get
			{
				return this._MAMANHINH;
			}
			set
			{
				if ((this._MAMANHINH != value))
				{
					this.OnMAMANHINHChanging(value);
					this.SendPropertyChanging();
					this._MAMANHINH = value;
					this.SendPropertyChanged("MAMANHINH");
					this.OnMAMANHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COQUYEN", DbType="Bit")]
		public System.Nullable<bool> COQUYEN
		{
			get
			{
				return this._COQUYEN;
			}
			set
			{
				if ((this._COQUYEN != value))
				{
					this.OnCOQUYENChanging(value);
					this.SendPropertyChanging();
					this._COQUYEN = value;
					this.SendPropertyChanged("COQUYEN");
					this.OnCOQUYENChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class HANG_HOA_TTCB
	{
		
		private string _MAMATHANG;
		
		private string _TENMATHANG;
		
		private int _SOLUONG;
		
		public HANG_HOA_TTCB()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMATHANG", CanBeNull=false)]
		public string MAMATHANG
		{
			get
			{
				return this._MAMATHANG;
			}
			set
			{
				if ((this._MAMATHANG != value))
				{
					this._MAMATHANG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENMATHANG", CanBeNull=false)]
		public string TENMATHANG
		{
			get
			{
				return this._TENMATHANG;
			}
			set
			{
				if ((this._TENMATHANG != value))
				{
					this._TENMATHANG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG")]
		public int SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this._SOLUONG = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHA_CUNG_CAP")]
	public partial class NHA_CUNG_CAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANCC;
		
		private string _TENNCC;
		
		private System.Nullable<decimal> _SODIENTHOAI;
		
		private string _DIACHI;
		
		private string _GHICHU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANCCChanging(string value);
    partial void OnMANCCChanged();
    partial void OnTENNCCChanging(string value);
    partial void OnTENNCCChanged();
    partial void OnSODIENTHOAIChanging(System.Nullable<decimal> value);
    partial void OnSODIENTHOAIChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    #endregion
		
		public NHA_CUNG_CAP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNCC", DbType="NVarChar(50)")]
		public string TENNCC
		{
			get
			{
				return this._TENNCC;
			}
			set
			{
				if ((this._TENNCC != value))
				{
					this.OnTENNCCChanging(value);
					this.SendPropertyChanging();
					this._TENNCC = value;
					this.SendPropertyChanged("TENNCC");
					this.OnTENNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODIENTHOAI", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SODIENTHOAI
		{
			get
			{
				return this._SODIENTHOAI;
			}
			set
			{
				if ((this._SODIENTHOAI != value))
				{
					this.OnSODIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._SODIENTHOAI = value;
					this.SendPropertyChanged("SODIENTHOAI");
					this.OnSODIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(50)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(50)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHAN_VIEN")]
	public partial class NHAN_VIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _TENDN;
		
		private string _CHUCVU;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private System.Nullable<decimal> _SODIENTHOAI;
		
		private System.Nullable<System.DateTime> _NGAYVAOLAM;
		
		private System.Nullable<double> _HESOLUONG;
		
		private System.Nullable<decimal> _LUONGCOBAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnSODIENTHOAIChanging(System.Nullable<decimal> value);
    partial void OnSODIENTHOAIChanged();
    partial void OnNGAYVAOLAMChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYVAOLAMChanged();
    partial void OnHESOLUONGChanging(System.Nullable<double> value);
    partial void OnHESOLUONGChanged();
    partial void OnLUONGCOBANChanging(System.Nullable<decimal> value);
    partial void OnLUONGCOBANChanged();
    #endregion
		
		public NHAN_VIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="Char(10)")]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="Char(10)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(5)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODIENTHOAI", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SODIENTHOAI
		{
			get
			{
				return this._SODIENTHOAI;
			}
			set
			{
				if ((this._SODIENTHOAI != value))
				{
					this.OnSODIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._SODIENTHOAI = value;
					this.SendPropertyChanged("SODIENTHOAI");
					this.OnSODIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYVAOLAM", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYVAOLAM
		{
			get
			{
				return this._NGAYVAOLAM;
			}
			set
			{
				if ((this._NGAYVAOLAM != value))
				{
					this.OnNGAYVAOLAMChanging(value);
					this.SendPropertyChanging();
					this._NGAYVAOLAM = value;
					this.SendPropertyChanged("NGAYVAOLAM");
					this.OnNGAYVAOLAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESOLUONG", DbType="Float")]
		public System.Nullable<double> HESOLUONG
		{
			get
			{
				return this._HESOLUONG;
			}
			set
			{
				if ((this._HESOLUONG != value))
				{
					this.OnHESOLUONGChanging(value);
					this.SendPropertyChanging();
					this._HESOLUONG = value;
					this.SendPropertyChanged("HESOLUONG");
					this.OnHESOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUONGCOBAN", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> LUONGCOBAN
		{
			get
			{
				return this._LUONGCOBAN;
			}
			set
			{
				if ((this._LUONGCOBAN != value))
				{
					this.OnLUONGCOBANChanging(value);
					this.SendPropertyChanging();
					this._LUONGCOBAN = value;
					this.SendPropertyChanged("LUONGCOBAN");
					this.OnLUONGCOBANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANG_HOA")]
	public partial class HANG_HOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAMATHANG;
		
		private string _TENMATHANG;
		
		private System.Nullable<int> _SOLUONG;
		
		private System.Nullable<decimal> _DONGIANHAP;
		
		private System.Nullable<decimal> _DONGIABAN;
		
		private string _GHICHU;
		
		private System.Nullable<System.DateTime> _NGAYSANXUAT;
		
		private System.Nullable<System.DateTime> _HANSUDUNG;
		
		private System.Nullable<System.DateTime> _NGAYNHAP;
		
		private string _MAKEHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAMATHANGChanging(string value);
    partial void OnMAMATHANGChanged();
    partial void OnTENMATHANGChanging(string value);
    partial void OnTENMATHANGChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnDONGIANHAPChanging(System.Nullable<decimal> value);
    partial void OnDONGIANHAPChanged();
    partial void OnDONGIABANChanging(System.Nullable<decimal> value);
    partial void OnDONGIABANChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    partial void OnNGAYSANXUATChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSANXUATChanged();
    partial void OnHANSUDUNGChanging(System.Nullable<System.DateTime> value);
    partial void OnHANSUDUNGChanged();
    partial void OnNGAYNHAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYNHAPChanged();
    partial void OnMAKEHANGChanging(string value);
    partial void OnMAKEHANGChanged();
    #endregion
		
		public HANG_HOA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMATHANG", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAMATHANG
		{
			get
			{
				return this._MAMATHANG;
			}
			set
			{
				if ((this._MAMATHANG != value))
				{
					this.OnMAMATHANGChanging(value);
					this.SendPropertyChanging();
					this._MAMATHANG = value;
					this.SendPropertyChanged("MAMATHANG");
					this.OnMAMATHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENMATHANG", DbType="NVarChar(50)")]
		public string TENMATHANG
		{
			get
			{
				return this._TENMATHANG;
			}
			set
			{
				if ((this._TENMATHANG != value))
				{
					this.OnTENMATHANGChanging(value);
					this.SendPropertyChanging();
					this._TENMATHANG = value;
					this.SendPropertyChanged("TENMATHANG");
					this.OnTENMATHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIANHAP", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DONGIANHAP
		{
			get
			{
				return this._DONGIANHAP;
			}
			set
			{
				if ((this._DONGIANHAP != value))
				{
					this.OnDONGIANHAPChanging(value);
					this.SendPropertyChanging();
					this._DONGIANHAP = value;
					this.SendPropertyChanged("DONGIANHAP");
					this.OnDONGIANHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DONGIABAN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> DONGIABAN
		{
			get
			{
				return this._DONGIABAN;
			}
			set
			{
				if ((this._DONGIABAN != value))
				{
					this.OnDONGIABANChanging(value);
					this.SendPropertyChanging();
					this._DONGIABAN = value;
					this.SendPropertyChanged("DONGIABAN");
					this.OnDONGIABANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(50)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSANXUAT", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSANXUAT
		{
			get
			{
				return this._NGAYSANXUAT;
			}
			set
			{
				if ((this._NGAYSANXUAT != value))
				{
					this.OnNGAYSANXUATChanging(value);
					this.SendPropertyChanging();
					this._NGAYSANXUAT = value;
					this.SendPropertyChanged("NGAYSANXUAT");
					this.OnNGAYSANXUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HANSUDUNG", DbType="Date")]
		public System.Nullable<System.DateTime> HANSUDUNG
		{
			get
			{
				return this._HANSUDUNG;
			}
			set
			{
				if ((this._HANSUDUNG != value))
				{
					this.OnHANSUDUNGChanging(value);
					this.SendPropertyChanging();
					this._HANSUDUNG = value;
					this.SendPropertyChanged("HANSUDUNG");
					this.OnHANSUDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYNHAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYNHAP
		{
			get
			{
				return this._NGAYNHAP;
			}
			set
			{
				if ((this._NGAYNHAP != value))
				{
					this.OnNGAYNHAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYNHAP = value;
					this.SendPropertyChanged("NGAYNHAP");
					this.OnNGAYNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKEHANG", DbType="Char(8) NOT NULL", CanBeNull=false)]
		public string MAKEHANG
		{
			get
			{
				return this._MAKEHANG;
			}
			set
			{
				if ((this._MAKEHANG != value))
				{
					this.OnMAKEHANGChanging(value);
					this.SendPropertyChanging();
					this._MAKEHANG = value;
					this.SendPropertyChanged("MAKEHANG");
					this.OnMAKEHANGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHI_TIET_PHIEU_XUAT")]
	public partial class CHI_TIET_PHIEU_XUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_CTPX;
		
		private string _MAHD;
		
		private string _MAMATHANG;
		
		private System.Nullable<decimal> _SOLUONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_CTPXChanging(string value);
    partial void OnMA_CTPXChanged();
    partial void OnMAHDChanging(string value);
    partial void OnMAHDChanged();
    partial void OnMAMATHANGChanging(string value);
    partial void OnMAMATHANGChanged();
    partial void OnSOLUONGChanging(System.Nullable<decimal> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public CHI_TIET_PHIEU_XUAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_CTPX", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_CTPX
		{
			get
			{
				return this._MA_CTPX;
			}
			set
			{
				if ((this._MA_CTPX != value))
				{
					this.OnMA_CTPXChanging(value);
					this.SendPropertyChanging();
					this._MA_CTPX = value;
					this.SendPropertyChanged("MA_CTPX");
					this.OnMA_CTPXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHD", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAHD
		{
			get
			{
				return this._MAHD;
			}
			set
			{
				if ((this._MAHD != value))
				{
					this.OnMAHDChanging(value);
					this.SendPropertyChanging();
					this._MAHD = value;
					this.SendPropertyChanged("MAHD");
					this.OnMAHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMATHANG", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MAMATHANG
		{
			get
			{
				return this._MAMATHANG;
			}
			set
			{
				if ((this._MAMATHANG != value))
				{
					this.OnMAMATHANGChanging(value);
					this.SendPropertyChanging();
					this._MAMATHANG = value;
					this.SendPropertyChanged("MAMATHANG");
					this.OnMAMATHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEU_XUAT_KHO")]
	public partial class PHIEU_XUAT_KHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHD;
		
		private string _MANV;
		
		private System.Nullable<System.DateTime> _NGAYLAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDChanging(string value);
    partial void OnMAHDChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnNGAYLAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPChanged();
    #endregion
		
		public PHIEU_XUAT_KHO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHD", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHD
		{
			get
			{
				return this._MAHD;
			}
			set
			{
				if ((this._MAHD != value))
				{
					this.OnMAHDChanging(value);
					this.SendPropertyChanging();
					this._MAHD = value;
					this.SendPropertyChanged("MAHD");
					this.OnMAHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAP", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYLAP
		{
			get
			{
				return this._NGAYLAP;
			}
			set
			{
				if ((this._NGAYLAP != value))
				{
					this.OnNGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAP = value;
					this.SendPropertyChanged("NGAYLAP");
					this.OnNGAYLAPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
